const fs=require('node:fs');
const assert=require('node:assert/strict');
const {webcrypto}=require('node:crypto');
global.crypto=webcrypto;
(async()=>{
 const text=fs.readFileSync(require('node:path').join(__dirname,'../central-control.js'),'utf8');
 const {CentralControl,routeControl}=await import('data:text/javascript;base64,'+Buffer.from(text).toString('base64'));
 const data=new Map();
 const storage={get:async k=>data.get(k),put:async(k,v)=>data.set(k,v),delete:async k=>{for(const id of Array.isArray(k)?k:[k])data.delete(id)},setAlarm:async()=>{},list:async({prefix='',limit=Infinity}={})=>new Map([...data].filter(([key])=>key.startsWith(prefix)).slice(0,limit)),transaction:async fn=>fn(storage)};
 const secret='fixture-password-do-not-use-in-production';
 const central=new CentralControl({storage},{CENTRAL_PASSWORD:secret});
 const req=(path,method='GET',body,token,headers={})=>new Request('https://worker.example/api/control/'+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...headers},...(body===undefined?{}:{body:typeof body==='string'||body instanceof Uint8Array?body:JSON.stringify(body)})});
 let response=await central.fetch(req('state'));assert.equal(response.status,200);assert.equal((await response.json()).mode,'auto');
 response=await central.fetch(req('state','PUT',{mode:'oculto',revision:0}));assert.equal(response.status,401);
 const unconfigured=new CentralControl({storage},{});response=await unconfigured.fetch(req('login','POST',{password:secret}));assert.equal(response.status,503);
 response=await routeControl(req('state'),{});assert.equal(response.status,503);
 response=await central.fetch(req('login','POST',{password:'wrong'}));assert.equal(response.status,401);
 response=await central.fetch(req('login','POST',{password:secret}));assert.equal(response.status,200);const token=(await response.json()).token;
 response=await central.fetch(req('state','PUT',{mode:'oculto',revision:0},token));assert.equal(response.status,200);assert.equal((await response.json()).revision,1);
 response=await central.fetch(req('state','PUT',{mode:'auto',revision:0},token));assert.equal(response.status,409);
 response=await central.fetch(req('state','PUT',{mode:'invalid',revision:1},token));assert.equal(response.status,400);
 response=await central.fetch(req('state','PUT',{message:'x'.repeat(401),revision:1},token));assert.equal(response.status,400);
 response=await central.fetch(req('state','PUT',{overlayUrl:'javascript:alert(1)',revision:1},token));assert.equal(response.status,400);
 response=await central.fetch(req('state','PUT',{message:'Boa competição!',mode:'auto',revision:1},token));assert.equal(response.status,200);
 response=await central.fetch(req('state','PUT',{mode:'oculto',revision:2},token+'bad'));assert.equal(response.status,401);
 response=await central.fetch(req('image','POST','<svg/>',token,{'Content-Type':'image/svg+xml'}));assert.equal(response.status,400);
 response=await central.fetch(req('image','POST',new Uint8Array(500*1024+1),token,{'Content-Type':'image/png'}));assert.equal(response.status,400);
 const png=Uint8Array.from([137,80,78,71,13,10,26,10]);
 response=await central.fetch(req('image','POST',png,token,{'Content-Type':'image/png'}));assert.equal(response.status,200);const imageUrl=(await response.json()).url;
 response=await central.fetch(new Request(imageUrl));assert.equal(response.status,200);assert.equal(response.headers.get('Content-Type'),'image/png');
 const second=new CentralControl({storage},{CENTRAL_PASSWORD:secret});response=await second.fetch(req('state'));assert.equal((await response.json()).message,'Boa competição!');
 response=await central.fetch(req('state?client=source-123&revision=2&mode=rodape&imageReady=1'));assert.equal(response.status,200);
 response=await central.fetch(req('status','GET',undefined,token));const status=await response.json();assert.equal(status.clients.length,1);assert.equal(status.clients[0].revision,2);
 for(let i=0;i<5;i++)await central.fetch(req('login','POST',{password:'wrong'}));response=await central.fetch(req('login','POST',{password:secret}));assert.equal(response.status,429);
 console.log('OK: autenticação, segredo ausente, limite de tentativas, revisão concorrente, persistência, validação, upload, heartbeat e comandos protegidos.');
})().catch(error=>{console.error(error);process.exitCode=1});
